#!/usr/bin/env python

import argparse
import pickle
import random
import shutil

parser = argparse.ArgumentParser(description='Build label list')
parser.add_argument('reference',type=argparse.FileType('rb'),help='The species and items reference')
parser.add_argument('offsets',type=argparse.FileType('rb'),help='The offsets to change')
parser.add_argument('-seed',type=str,help='The seed of the randomization')
parser.add_argument('rom',type=str,help='The name of the base rom file')
parser.add_argument('randomized',type=str,help='The name of the output rom file')

args = parser.parse_args()

(species,items) = pickle.load(args.reference)
args.reference.close()

(pkmn_offsets,item_offsets) = pickle.load(args.offsets)
args.offsets.close()

mon_options = [
		species['SPECIES_BULBASAUR'],
		species['SPECIES_IVYSAUR'],
		species['SPECIES_VENUSAUR'],
		species['SPECIES_CHARMANDER'],
		species['SPECIES_CHARMELEON'],
		species['SPECIES_CHARIZARD'],
		species['SPECIES_SQUIRTLE'],
		species['SPECIES_WARTORTLE'],
		species['SPECIES_BLASTOISE'],
		species['SPECIES_CATERPIE'],
		species['SPECIES_METAPOD'],
		species['SPECIES_BUTTERFREE'],
		species['SPECIES_WEEDLE'],
		species['SPECIES_KAKUNA'],
		species['SPECIES_BEEDRILL'],
		species['SPECIES_PIDGEY'],
		species['SPECIES_PIDGEOTTO'],
		species['SPECIES_PIDGEOT'],
		species['SPECIES_RATTATA'],
		species['SPECIES_RATICATE'],
		species['SPECIES_SPEAROW'],
		species['SPECIES_FEAROW'],
		species['SPECIES_EKANS'],
		species['SPECIES_ARBOK'],
		species['SPECIES_PIKACHU'],
		species['SPECIES_RAICHU'],
		species['SPECIES_SANDSHREW'],
		species['SPECIES_SANDSLASH'],
		species['SPECIES_NIDORAN_F'],
		species['SPECIES_NIDORINA'],
		species['SPECIES_NIDOQUEEN'],
		species['SPECIES_NIDORAN_M'],
		species['SPECIES_NIDORINO'],
		species['SPECIES_NIDOKING'],
		species['SPECIES_CLEFAIRY'],
		species['SPECIES_CLEFABLE'],
		species['SPECIES_VULPIX'],
		species['SPECIES_NINETALES'],
		species['SPECIES_JIGGLYPUFF'],
		species['SPECIES_WIGGLYTUFF'],
		species['SPECIES_ZUBAT'],
		species['SPECIES_GOLBAT'],
		species['SPECIES_ODDISH'],
		species['SPECIES_GLOOM'],
		species['SPECIES_VILEPLUME'],
		species['SPECIES_PARAS'],
		species['SPECIES_PARASECT'],
		species['SPECIES_VENONAT'],
		species['SPECIES_VENOMOTH'],
		species['SPECIES_DIGLETT'],
		species['SPECIES_DUGTRIO'],
		species['SPECIES_MEOWTH'],
		species['SPECIES_PERSIAN'],
		species['SPECIES_PSYDUCK'],
		species['SPECIES_GOLDUCK'],
		species['SPECIES_MANKEY'],
		species['SPECIES_PRIMEAPE'],
		species['SPECIES_GROWLITHE'],
		species['SPECIES_ARCANINE'],
		species['SPECIES_POLIWAG'],
		species['SPECIES_POLIWHIRL'],
		species['SPECIES_POLIWRATH'],
		species['SPECIES_ABRA'],
		species['SPECIES_KADABRA'],
		species['SPECIES_ALAKAZAM'],
		species['SPECIES_MACHOP'],
		species['SPECIES_MACHOKE'],
		species['SPECIES_MACHAMP'],
		species['SPECIES_BELLSPROUT'],
		species['SPECIES_WEEPINBELL'],
		species['SPECIES_VICTREEBEL'],
		species['SPECIES_TENTACOOL'],
		species['SPECIES_TENTACRUEL'],
		species['SPECIES_GEODUDE'],
		species['SPECIES_GRAVELER'],
		species['SPECIES_GOLEM'],
		species['SPECIES_PONYTA'],
		species['SPECIES_RAPIDASH'],
		species['SPECIES_SLOWPOKE'],
		species['SPECIES_SLOWBRO'],
		species['SPECIES_MAGNEMITE'],
		species['SPECIES_MAGNETON'],
		species['SPECIES_FARFETCHD'],
		species['SPECIES_DODUO'],
		species['SPECIES_DODRIO'],
		species['SPECIES_SEEL'],
		species['SPECIES_DEWGONG'],
		species['SPECIES_GRIMER'],
		species['SPECIES_MUK'],
		species['SPECIES_SHELLDER'],
		species['SPECIES_CLOYSTER'],
		species['SPECIES_GASTLY'],
		species['SPECIES_HAUNTER'],
		species['SPECIES_GENGAR'],
		species['SPECIES_ONIX'],
		species['SPECIES_DROWZEE'],
		species['SPECIES_HYPNO'],
		species['SPECIES_KRABBY'],
		species['SPECIES_KINGLER'],
		species['SPECIES_VOLTORB'],
		species['SPECIES_ELECTRODE'],
		species['SPECIES_EXEGGCUTE'],
		species['SPECIES_EXEGGUTOR'],
		species['SPECIES_CUBONE'],
		species['SPECIES_MAROWAK'],
		species['SPECIES_HITMONLEE'],
		species['SPECIES_HITMONCHAN'],
		species['SPECIES_LICKITUNG'],
		species['SPECIES_KOFFING'],
		species['SPECIES_WEEZING'],
		species['SPECIES_RHYHORN'],
		species['SPECIES_RHYDON'],
		species['SPECIES_CHANSEY'],
		species['SPECIES_TANGELA'],
		species['SPECIES_KANGASKHAN'],
		species['SPECIES_HORSEA'],
		species['SPECIES_SEADRA'],
		species['SPECIES_GOLDEEN'],
		species['SPECIES_SEAKING'],
		species['SPECIES_STARYU'],
		species['SPECIES_STARMIE'],
		species['SPECIES_MR_MIME'],
		species['SPECIES_SCYTHER'],
		species['SPECIES_JYNX'],
		species['SPECIES_ELECTABUZZ'],
		species['SPECIES_MAGMAR'],
		species['SPECIES_PINSIR'],
		species['SPECIES_TAUROS'],
		species['SPECIES_MAGIKARP'],
		species['SPECIES_GYARADOS'],
		species['SPECIES_LAPRAS'],
		species['SPECIES_DITTO'],
		species['SPECIES_EEVEE'],
		species['SPECIES_VAPOREON'],
		species['SPECIES_JOLTEON'],
		species['SPECIES_FLAREON'],
		species['SPECIES_PORYGON'],
		species['SPECIES_OMANYTE'],
		species['SPECIES_OMASTAR'],
		species['SPECIES_KABUTO'],
		species['SPECIES_KABUTOPS'],
		species['SPECIES_AERODACTYL'],
		species['SPECIES_SNORLAX'],
		species['SPECIES_ARTICUNO'],
		species['SPECIES_ZAPDOS'],
		species['SPECIES_MOLTRES'],
		species['SPECIES_DRATINI'],
		species['SPECIES_DRAGONAIR'],
		species['SPECIES_DRAGONITE'],
		species['SPECIES_MEWTWO'],
		species['SPECIES_MEW'],
		species['SPECIES_CHIKORITA'],
		species['SPECIES_BAYLEEF'],
		species['SPECIES_MEGANIUM'],
		species['SPECIES_CYNDAQUIL'],
		species['SPECIES_QUILAVA'],
		species['SPECIES_TYPHLOSION'],
		species['SPECIES_TOTODILE'],
		species['SPECIES_CROCONAW'],
		species['SPECIES_FERALIGATR'],
		species['SPECIES_SENTRET'],
		species['SPECIES_FURRET'],
		species['SPECIES_HOOTHOOT'],
		species['SPECIES_NOCTOWL'],
		species['SPECIES_LEDYBA'],
		species['SPECIES_LEDIAN'],
		species['SPECIES_SPINARAK'],
		species['SPECIES_ARIADOS'],
		species['SPECIES_CROBAT'],
		species['SPECIES_CHINCHOU'],
		species['SPECIES_LANTURN'],
		species['SPECIES_PICHU'],
		species['SPECIES_CLEFFA'],
		species['SPECIES_IGGLYBUFF'],
		species['SPECIES_TOGEPI'],
		species['SPECIES_TOGETIC'],
		species['SPECIES_NATU'],
		species['SPECIES_XATU'],
		species['SPECIES_MAREEP'],
		species['SPECIES_FLAAFFY'],
		species['SPECIES_AMPHAROS'],
		species['SPECIES_BELLOSSOM'],
		species['SPECIES_MARILL'],
		species['SPECIES_AZUMARILL'],
		species['SPECIES_SUDOWOODO'],
		species['SPECIES_POLITOED'],
		species['SPECIES_HOPPIP'],
		species['SPECIES_SKIPLOOM'],
		species['SPECIES_JUMPLUFF'],
		species['SPECIES_AIPOM'],
		species['SPECIES_SUNKERN'],
		species['SPECIES_SUNFLORA'],
		species['SPECIES_YANMA'],
		species['SPECIES_WOOPER'],
		species['SPECIES_QUAGSIRE'],
		species['SPECIES_ESPEON'],
		species['SPECIES_UMBREON'],
		species['SPECIES_MURKROW'],
		species['SPECIES_SLOWKING'],
		species['SPECIES_MISDREAVUS'],
		species['SPECIES_UNOWN'],
		species['SPECIES_WOBBUFFET'],
		species['SPECIES_GIRAFARIG'],
		species['SPECIES_PINECO'],
		species['SPECIES_FORRETRESS'],
		species['SPECIES_DUNSPARCE'],
		species['SPECIES_GLIGAR'],
		species['SPECIES_STEELIX'],
		species['SPECIES_SNUBBULL'],
		species['SPECIES_GRANBULL'],
		species['SPECIES_QWILFISH'],
		species['SPECIES_SCIZOR'],
		species['SPECIES_SHUCKLE'],
		species['SPECIES_HERACROSS'],
		species['SPECIES_SNEASEL'],
		species['SPECIES_TEDDIURSA'],
		species['SPECIES_URSARING'],
		species['SPECIES_SLUGMA'],
		species['SPECIES_MAGCARGO'],
		species['SPECIES_SWINUB'],
		species['SPECIES_PILOSWINE'],
		species['SPECIES_CORSOLA'],
		species['SPECIES_REMORAID'],
		species['SPECIES_OCTILLERY'],
		species['SPECIES_DELIBIRD'],
		species['SPECIES_MANTINE'],
		species['SPECIES_SKARMORY'],
		species['SPECIES_HOUNDOUR'],
		species['SPECIES_HOUNDOOM'],
		species['SPECIES_KINGDRA'],
		species['SPECIES_PHANPY'],
		species['SPECIES_DONPHAN'],
		species['SPECIES_PORYGON2'],
		species['SPECIES_STANTLER'],
		species['SPECIES_SMEARGLE'],
		species['SPECIES_TYROGUE'],
		species['SPECIES_HITMONTOP'],
		species['SPECIES_SMOOCHUM'],
		species['SPECIES_ELEKID'],
		species['SPECIES_MAGBY'],
		species['SPECIES_MILTANK'],
		species['SPECIES_BLISSEY'],
		species['SPECIES_RAIKOU'],
		species['SPECIES_ENTEI'],
		species['SPECIES_SUICUNE'],
		species['SPECIES_LARVITAR'],
		species['SPECIES_PUPITAR'],
		species['SPECIES_TYRANITAR'],
		species['SPECIES_LUGIA'],
		species['SPECIES_HO_OH'],
		species['SPECIES_CELEBI'],
		species['SPECIES_TREECKO'],
		species['SPECIES_GROVYLE'],
		species['SPECIES_SCEPTILE'],
		species['SPECIES_TORCHIC'],
		species['SPECIES_COMBUSKEN'],
		species['SPECIES_BLAZIKEN'],
		species['SPECIES_MUDKIP'],
		species['SPECIES_MARSHTOMP'],
		species['SPECIES_SWAMPERT'],
		species['SPECIES_POOCHYENA'],
		species['SPECIES_MIGHTYENA'],
		species['SPECIES_ZIGZAGOON'],
		species['SPECIES_LINOONE'],
		species['SPECIES_WURMPLE'],
		species['SPECIES_SILCOON'],
		species['SPECIES_BEAUTIFLY'],
		species['SPECIES_CASCOON'],
		species['SPECIES_DUSTOX'],
		species['SPECIES_LOTAD'],
		species['SPECIES_LOMBRE'],
		species['SPECIES_LUDICOLO'],
		species['SPECIES_SEEDOT'],
		species['SPECIES_NUZLEAF'],
		species['SPECIES_SHIFTRY'],
		species['SPECIES_TAILLOW'],
		species['SPECIES_SWELLOW'],
		species['SPECIES_WINGULL'],
		species['SPECIES_PELIPPER'],
		species['SPECIES_RALTS'],
		species['SPECIES_KIRLIA'],
		species['SPECIES_GARDEVOIR'],
		species['SPECIES_SURSKIT'],
		species['SPECIES_MASQUERAIN'],
		species['SPECIES_SHROOMISH'],
		species['SPECIES_BRELOOM'],
		species['SPECIES_SLAKOTH'],
		species['SPECIES_VIGOROTH'],
		species['SPECIES_SLAKING'],
		species['SPECIES_NINCADA'],
		species['SPECIES_NINJASK'],
		species['SPECIES_SHEDINJA'],
		species['SPECIES_WHISMUR'],
		species['SPECIES_LOUDRED'],
		species['SPECIES_EXPLOUD'],
		species['SPECIES_MAKUHITA'],
		species['SPECIES_HARIYAMA'],
		species['SPECIES_AZURILL'],
		species['SPECIES_NOSEPASS'],
		species['SPECIES_SKITTY'],
		species['SPECIES_DELCATTY'],
		species['SPECIES_SABLEYE'],
		species['SPECIES_MAWILE'],
		species['SPECIES_ARON'],
		species['SPECIES_LAIRON'],
		species['SPECIES_AGGRON'],
		species['SPECIES_MEDITITE'],
		species['SPECIES_MEDICHAM'],
		species['SPECIES_ELECTRIKE'],
		species['SPECIES_MANECTRIC'],
		species['SPECIES_PLUSLE'],
		species['SPECIES_MINUN'],
		species['SPECIES_VOLBEAT'],
		species['SPECIES_ILLUMISE'],
		species['SPECIES_ROSELIA'],
		species['SPECIES_GULPIN'],
		species['SPECIES_SWALOT'],
		species['SPECIES_CARVANHA'],
		species['SPECIES_SHARPEDO'],
		species['SPECIES_WAILMER'],
		species['SPECIES_WAILORD'],
		species['SPECIES_NUMEL'],
		species['SPECIES_CAMERUPT'],
		species['SPECIES_TORKOAL'],
		species['SPECIES_SPOINK'],
		species['SPECIES_GRUMPIG'],
		species['SPECIES_SPINDA'],
		species['SPECIES_TRAPINCH'],
		species['SPECIES_VIBRAVA'],
		species['SPECIES_FLYGON'],
		species['SPECIES_CACNEA'],
		species['SPECIES_CACTURNE'],
		species['SPECIES_SWABLU'],
		species['SPECIES_ALTARIA'],
		species['SPECIES_ZANGOOSE'],
		species['SPECIES_SEVIPER'],
		species['SPECIES_LUNATONE'],
		species['SPECIES_SOLROCK'],
		species['SPECIES_BARBOACH'],
		species['SPECIES_WHISCASH'],
		species['SPECIES_CORPHISH'],
		species['SPECIES_CRAWDAUNT'],
		species['SPECIES_BALTOY'],
		species['SPECIES_CLAYDOL'],
		species['SPECIES_LILEEP'],
		species['SPECIES_CRADILY'],
		species['SPECIES_ANORITH'],
		species['SPECIES_ARMALDO'],
		species['SPECIES_FEEBAS'],
		species['SPECIES_MILOTIC'],
		species['SPECIES_CASTFORM'],
		species['SPECIES_KECLEON'],
		species['SPECIES_SHUPPET'],
		species['SPECIES_BANETTE'],
		species['SPECIES_DUSKULL'],
		species['SPECIES_DUSCLOPS'],
		species['SPECIES_TROPIUS'],
		species['SPECIES_CHIMECHO'],
		species['SPECIES_ABSOL'],
		species['SPECIES_WYNAUT'],
		species['SPECIES_SNORUNT'],
		species['SPECIES_GLALIE'],
		species['SPECIES_SPHEAL'],
		species['SPECIES_SEALEO'],
		species['SPECIES_WALREIN'],
		species['SPECIES_CLAMPERL'],
		species['SPECIES_HUNTAIL'],
		species['SPECIES_GOREBYSS'],
		species['SPECIES_RELICANTH'],
		species['SPECIES_LUVDISC'],
		species['SPECIES_BAGON'],
		species['SPECIES_SHELGON'],
		species['SPECIES_SALAMENCE'],
		species['SPECIES_BELDUM'],
		species['SPECIES_METANG'],
		species['SPECIES_METAGROSS'],
		species['SPECIES_REGIROCK'],
		species['SPECIES_REGICE'],
		species['SPECIES_REGISTEEL'],
		species['SPECIES_LATIAS'],
		species['SPECIES_LATIOS'],
		species['SPECIES_KYOGRE'],
		species['SPECIES_GROUDON'],
		species['SPECIES_RAYQUAZA'],
		species['SPECIES_JIRACHI'],
		species['SPECIES_DEOXYS'],
		species['SPECIES_TURTWIG'],
		species['SPECIES_GROTLE'],
		species['SPECIES_TORTERRA'],
		species['SPECIES_CHIMCHAR'],
		species['SPECIES_MONFERNO'],
		species['SPECIES_INFERNAPE'],
		species['SPECIES_PIPLUP'],
		species['SPECIES_PRINPLUP'],
		species['SPECIES_EMPOLEON'],
		species['SPECIES_STARLY'],
		species['SPECIES_STARAVIA'],
		species['SPECIES_STARAPTOR'],
		species['SPECIES_BIDOOF'],
		species['SPECIES_BIBAREL'],
		species['SPECIES_KRICKETOT'],
		species['SPECIES_KRICKETUNE'],
		species['SPECIES_SHINX'],
		species['SPECIES_LUXIO'],
		species['SPECIES_LUXRAY'],
		species['SPECIES_BUDEW'],
		species['SPECIES_ROSERADE'],
		species['SPECIES_CRANIDOS'],
		species['SPECIES_RAMPARDOS'],
		species['SPECIES_SHIELDON'],
		species['SPECIES_BASTIODON'],
		species['SPECIES_BURMY'],
		species['SPECIES_WORMADAM'],
		species['SPECIES_MOTHIM'],
		species['SPECIES_COMBEE'],
		species['SPECIES_VESPIQUEN'],
		species['SPECIES_PACHIRISU'],
		species['SPECIES_BUIZEL'],
		species['SPECIES_FLOATZEL'],
		species['SPECIES_CHERUBI'],
		species['SPECIES_CHERRIM'],
		species['SPECIES_SHELLOS'],
		species['SPECIES_GASTRODON'],
		species['SPECIES_AMBIPOM'],
		species['SPECIES_DRIFLOON'],
		species['SPECIES_DRIFBLIM'],
		species['SPECIES_BUNEARY'],
		species['SPECIES_LOPUNNY'],
		species['SPECIES_MISMAGIUS'],
		species['SPECIES_HONCHKROW'],
		species['SPECIES_GLAMEOW'],
		species['SPECIES_PURUGLY'],
		species['SPECIES_CHINGLING'],
		species['SPECIES_STUNKY'],
		species['SPECIES_SKUNTANK'],
		species['SPECIES_BRONZOR'],
		species['SPECIES_BRONZONG'],
		species['SPECIES_BONSLY'],
		species['SPECIES_MIME_JR'],
		species['SPECIES_HAPPINY'],
		species['SPECIES_CHATOT'],
		species['SPECIES_SPIRITOMB'],
		species['SPECIES_GIBLE'],
		species['SPECIES_GABITE'],
		species['SPECIES_GARCHOMP'],
		species['SPECIES_MUNCHLAX'],
		species['SPECIES_RIOLU'],
		species['SPECIES_LUCARIO'],
		species['SPECIES_HIPPOPOTAS'],
		species['SPECIES_HIPPOWDON'],
		species['SPECIES_SKORUPI'],
		species['SPECIES_DRAPION'],
		species['SPECIES_CROAGUNK'],
		species['SPECIES_TOXICROAK'],
		species['SPECIES_CARNIVINE'],
		species['SPECIES_FINNEON'],
		species['SPECIES_LUMINEON'],
		species['SPECIES_MANTYKE'],
		species['SPECIES_SNOVER'],
		species['SPECIES_ABOMASNOW'],
		species['SPECIES_WEAVILE'],
		species['SPECIES_MAGNEZONE'],
		species['SPECIES_LICKILICKY'],
		species['SPECIES_RHYPERIOR'],
		species['SPECIES_TANGROWTH'],
		species['SPECIES_ELECTIVIRE'],
		species['SPECIES_MAGMORTAR'],
		species['SPECIES_TOGEKISS'],
		species['SPECIES_YANMEGA'],
		species['SPECIES_LEAFEON'],
		species['SPECIES_GLACEON'],
		species['SPECIES_GLISCOR'],
		species['SPECIES_MAMOSWINE'],
		species['SPECIES_PORYGON_Z'],
		species['SPECIES_GALLADE'],
		species['SPECIES_PROBOPASS'],
		species['SPECIES_DUSKNOIR'],
		species['SPECIES_FROSLASS'],
		species['SPECIES_ROTOM'],
		species['SPECIES_UXIE'],
		species['SPECIES_MESPRIT'],
		species['SPECIES_AZELF'],
		species['SPECIES_DIALGA'],
		species['SPECIES_PALKIA'],
		species['SPECIES_HEATRAN'],
		species['SPECIES_REGIGIGAS'],
		species['SPECIES_GIRATINA'],
		species['SPECIES_CRESSELIA'],
		species['SPECIES_PHIONE'],
		species['SPECIES_MANAPHY'],
		species['SPECIES_DARKRAI'],
		species['SPECIES_SHAYMIN'],
		species['SPECIES_ARCEUS'],
		species['SPECIES_VICTINI'],
		species['SPECIES_SNIVY'],
		species['SPECIES_SERVINE'],
		species['SPECIES_SERPERIOR'],
		species['SPECIES_TEPIG'],
		species['SPECIES_PIGNITE'],
		species['SPECIES_EMBOAR'],
		species['SPECIES_OSHAWOTT'],
		species['SPECIES_DEWOTT'],
		species['SPECIES_SAMUROTT'],
		species['SPECIES_PATRAT'],
		species['SPECIES_WATCHOG'],
		species['SPECIES_LILLIPUP'],
		species['SPECIES_HERDIER'],
		species['SPECIES_STOUTLAND'],
		species['SPECIES_PURRLOIN'],
		species['SPECIES_LIEPARD'],
		species['SPECIES_PANSAGE'],
		species['SPECIES_SIMISAGE'],
		species['SPECIES_PANSEAR'],
		species['SPECIES_SIMISEAR'],
		species['SPECIES_PANPOUR'],
		species['SPECIES_SIMIPOUR'],
		species['SPECIES_MUNNA'],
		species['SPECIES_MUSHARNA'],
		species['SPECIES_PIDOVE'],
		species['SPECIES_TRANQUILL'],
		species['SPECIES_UNFEZANT'],
		species['SPECIES_BLITZLE'],
		species['SPECIES_ZEBSTRIKA'],
		species['SPECIES_ROGGENROLA'],
		species['SPECIES_BOLDORE'],
		species['SPECIES_GIGALITH'],
		species['SPECIES_WOOBAT'],
		species['SPECIES_SWOOBAT'],
		species['SPECIES_DRILBUR'],
		species['SPECIES_EXCADRILL'],
		species['SPECIES_AUDINO'],
		species['SPECIES_TIMBURR'],
		species['SPECIES_GURDURR'],
		species['SPECIES_CONKELDURR'],
		species['SPECIES_TYMPOLE'],
		species['SPECIES_PALPITOAD'],
		species['SPECIES_SEISMITOAD'],
		species['SPECIES_THROH'],
		species['SPECIES_SAWK'],
		species['SPECIES_SEWADDLE'],
		species['SPECIES_SWADLOON'],
		species['SPECIES_LEAVANNY'],
		species['SPECIES_VENIPEDE'],
		species['SPECIES_WHIRLIPEDE'],
		species['SPECIES_SCOLIPEDE'],
		species['SPECIES_COTTONEE'],
		species['SPECIES_WHIMSICOTT'],
		species['SPECIES_PETILIL'],
		species['SPECIES_LILLIGANT'],
		species['SPECIES_BASCULIN'],
		species['SPECIES_SANDILE'],
		species['SPECIES_KROKOROK'],
		species['SPECIES_KROOKODILE'],
		species['SPECIES_DARUMAKA'],
		species['SPECIES_DARMANITAN'],
		species['SPECIES_MARACTUS'],
		species['SPECIES_DWEBBLE'],
		species['SPECIES_CRUSTLE'],
		species['SPECIES_SCRAGGY'],
		species['SPECIES_SCRAFTY'],
		species['SPECIES_SIGILYPH'],
		species['SPECIES_YAMASK'],
		species['SPECIES_COFAGRIGUS'],
		species['SPECIES_TIRTOUGA'],
		species['SPECIES_CARRACOSTA'],
		species['SPECIES_ARCHEN'],
		species['SPECIES_ARCHEOPS'],
		species['SPECIES_TRUBBISH'],
		species['SPECIES_GARBODOR'],
		species['SPECIES_ZORUA'],
		species['SPECIES_ZOROARK'],
		species['SPECIES_MINCCINO'],
		species['SPECIES_CINCCINO'],
		species['SPECIES_GOTHITA'],
		species['SPECIES_GOTHORITA'],
		species['SPECIES_GOTHITELLE'],
		species['SPECIES_SOLOSIS'],
		species['SPECIES_DUOSION'],
		species['SPECIES_REUNICLUS'],
		species['SPECIES_DUCKLETT'],
		species['SPECIES_SWANNA'],
		species['SPECIES_VANILLITE'],
		species['SPECIES_VANILLISH'],
		species['SPECIES_VANILLUXE'],
		species['SPECIES_DEERLING'],
		species['SPECIES_SAWSBUCK'],
		species['SPECIES_EMOLGA'],
		species['SPECIES_KARRABLAST'],
		species['SPECIES_ESCAVALIER'],
		species['SPECIES_FOONGUS'],
		species['SPECIES_AMOONGUSS'],
		species['SPECIES_FRILLISH'],
		species['SPECIES_JELLICENT'],
		species['SPECIES_ALOMOMOLA'],
		species['SPECIES_JOLTIK'],
		species['SPECIES_GALVANTULA'],
		species['SPECIES_FERROSEED'],
		species['SPECIES_FERROTHORN'],
		species['SPECIES_KLINK'],
		species['SPECIES_KLANG'],
		species['SPECIES_KLINKLANG'],
		species['SPECIES_TYNAMO'],
		species['SPECIES_EELEKTRIK'],
		species['SPECIES_EELEKTROSS'],
		species['SPECIES_ELGYEM'],
		species['SPECIES_BEHEEYEM'],
		species['SPECIES_LITWICK'],
		species['SPECIES_LAMPENT'],
		species['SPECIES_CHANDELURE'],
		species['SPECIES_AXEW'],
		species['SPECIES_FRAXURE'],
		species['SPECIES_HAXORUS'],
		species['SPECIES_CUBCHOO'],
		species['SPECIES_BEARTIC'],
		species['SPECIES_CRYOGONAL'],
		species['SPECIES_SHELMET'],
		species['SPECIES_ACCELGOR'],
		species['SPECIES_STUNFISK'],
		species['SPECIES_MIENFOO'],
		species['SPECIES_MIENSHAO'],
		species['SPECIES_DRUDDIGON'],
		species['SPECIES_GOLETT'],
		species['SPECIES_GOLURK'],
		species['SPECIES_PAWNIARD'],
		species['SPECIES_BISHARP'],
		species['SPECIES_BOUFFALANT'],
		species['SPECIES_RUFFLET'],
		species['SPECIES_BRAVIARY'],
		species['SPECIES_VULLABY'],
		species['SPECIES_MANDIBUZZ'],
		species['SPECIES_HEATMOR'],
		species['SPECIES_DURANT'],
		species['SPECIES_DEINO'],
		species['SPECIES_ZWEILOUS'],
		species['SPECIES_HYDREIGON'],
		species['SPECIES_LARVESTA'],
		species['SPECIES_VOLCARONA'],
		species['SPECIES_COBALION'],
		species['SPECIES_TERRAKION'],
		species['SPECIES_VIRIZION'],
		species['SPECIES_TORNADUS'],
		species['SPECIES_THUNDURUS'],
		species['SPECIES_RESHIRAM'],
		species['SPECIES_ZEKROM'],
		species['SPECIES_LANDORUS'],
		species['SPECIES_KYUREM'],
		species['SPECIES_KELDEO'],
		species['SPECIES_MELOETTA'],
		species['SPECIES_GENESECT'],
		species['SPECIES_CHESPIN'],
		species['SPECIES_QUILLADIN'],
		species['SPECIES_CHESNAUGHT'],
		species['SPECIES_FENNEKIN'],
		species['SPECIES_BRAIXEN'],
		species['SPECIES_DELPHOX'],
		species['SPECIES_FROAKIE'],
		species['SPECIES_FROGADIER'],
		species['SPECIES_GRENINJA'],
		species['SPECIES_BUNNELBY'],
		species['SPECIES_DIGGERSBY'],
		species['SPECIES_FLETCHLING'],
		species['SPECIES_FLETCHINDER'],
		species['SPECIES_TALONFLAME'],
		species['SPECIES_SCATTERBUG'],
		species['SPECIES_SPEWPA'],
		species['SPECIES_VIVILLON'],
		species['SPECIES_LITLEO'],
		species['SPECIES_PYROAR'],
		species['SPECIES_FLABEBE'],
		species['SPECIES_FLOETTE'],
		species['SPECIES_FLORGES'],
		species['SPECIES_SKIDDO'],
		species['SPECIES_GOGOAT'],
		species['SPECIES_PANCHAM'],
		species['SPECIES_PANGORO'],
		species['SPECIES_FURFROU'],
		species['SPECIES_ESPURR'],
		species['SPECIES_MEOWSTIC'],
		species['SPECIES_HONEDGE'],
		species['SPECIES_DOUBLADE'],
		species['SPECIES_AEGISLASH'],
		species['SPECIES_SPRITZEE'],
		species['SPECIES_AROMATISSE'],
		species['SPECIES_SWIRLIX'],
		species['SPECIES_SLURPUFF'],
		species['SPECIES_INKAY'],
		species['SPECIES_MALAMAR'],
		species['SPECIES_BINACLE'],
		species['SPECIES_BARBARACLE'],
		species['SPECIES_SKRELP'],
		species['SPECIES_DRAGALGE'],
		species['SPECIES_CLAUNCHER'],
		species['SPECIES_CLAWITZER'],
		species['SPECIES_HELIOPTILE'],
		species['SPECIES_HELIOLISK'],
		species['SPECIES_TYRUNT'],
		species['SPECIES_TYRANTRUM'],
		species['SPECIES_AMAURA'],
		species['SPECIES_AURORUS'],
		species['SPECIES_SYLVEON'],
		species['SPECIES_HAWLUCHA'],
		species['SPECIES_DEDENNE'],
		species['SPECIES_CARBINK'],
		species['SPECIES_GOOMY'],
		species['SPECIES_SLIGGOO'],
		species['SPECIES_GOODRA'],
		species['SPECIES_KLEFKI'],
		species['SPECIES_PHANTUMP'],
		species['SPECIES_TREVENANT'],
		species['SPECIES_PUMPKABOO'],
		species['SPECIES_GOURGEIST'],
		species['SPECIES_BERGMITE'],
		species['SPECIES_AVALUGG'],
		species['SPECIES_NOIBAT'],
		species['SPECIES_NOIVERN'],
		species['SPECIES_XERNEAS'],
		species['SPECIES_YVELTAL'],
		species['SPECIES_ZYGARDE'],
		species['SPECIES_DIANCIE'],
		species['SPECIES_HOOPA'],
		species['SPECIES_VOLCANION'],
		species['SPECIES_ROWLET'],
		species['SPECIES_DARTRIX'],
		species['SPECIES_DECIDUEYE'],
		species['SPECIES_LITTEN'],
		species['SPECIES_TORRACAT'],
		species['SPECIES_INCINEROAR'],
		species['SPECIES_POPPLIO'],
		species['SPECIES_BRIONNE'],
		species['SPECIES_PRIMARINA'],
		species['SPECIES_PIKIPEK'],
		species['SPECIES_TRUMBEAK'],
		species['SPECIES_TOUCANNON'],
		species['SPECIES_YUNGOOS'],
		species['SPECIES_GUMSHOOS'],
		species['SPECIES_GRUBBIN'],
		species['SPECIES_CHARJABUG'],
		species['SPECIES_VIKAVOLT'],
		species['SPECIES_CRABRAWLER'],
		species['SPECIES_CRABOMINABLE'],
		species['SPECIES_ORICORIO'],
		species['SPECIES_CUTIEFLY'],
		species['SPECIES_RIBOMBEE'],
		species['SPECIES_ROCKRUFF'],
		species['SPECIES_LYCANROC'],
		species['SPECIES_WISHIWASHI'],
		species['SPECIES_MAREANIE'],
		species['SPECIES_TOXAPEX'],
		species['SPECIES_MUDBRAY'],
		species['SPECIES_MUDSDALE'],
		species['SPECIES_DEWPIDER'],
		species['SPECIES_ARAQUANID'],
		species['SPECIES_FOMANTIS'],
		species['SPECIES_LURANTIS'],
		species['SPECIES_MORELULL'],
		species['SPECIES_SHIINOTIC'],
		species['SPECIES_SALANDIT'],
		species['SPECIES_SALAZZLE'],
		species['SPECIES_STUFFUL'],
		species['SPECIES_BEWEAR'],
		species['SPECIES_BOUNSWEET'],
		species['SPECIES_STEENEE'],
		species['SPECIES_TSAREENA'],
		species['SPECIES_COMFEY'],
		species['SPECIES_ORANGURU'],
		species['SPECIES_PASSIMIAN'],
		species['SPECIES_WIMPOD'],
		species['SPECIES_GOLISOPOD'],
		species['SPECIES_SANDYGAST'],
		species['SPECIES_PALOSSAND'],
		species['SPECIES_PYUKUMUKU'],
		species['SPECIES_TYPE_NULL'],
		species['SPECIES_SILVALLY'],
		species['SPECIES_MINIOR'],
		species['SPECIES_KOMALA'],
		species['SPECIES_TURTONATOR'],
		species['SPECIES_TOGEDEMARU'],
		species['SPECIES_MIMIKYU'],
		species['SPECIES_BRUXISH'],
		species['SPECIES_DRAMPA'],
		species['SPECIES_DHELMISE'],
		species['SPECIES_JANGMO_O'],
		species['SPECIES_HAKAMO_O'],
		species['SPECIES_KOMMO_O'],
		species['SPECIES_TAPU_KOKO'],
		species['SPECIES_TAPU_LELE'],
		species['SPECIES_TAPU_BULU'],
		species['SPECIES_TAPU_FINI'],
		species['SPECIES_COSMOG'],
		species['SPECIES_COSMOEM'],
		species['SPECIES_SOLGALEO'],
		species['SPECIES_LUNALA'],
		species['SPECIES_NIHILEGO'],
		species['SPECIES_BUZZWOLE'],
		species['SPECIES_PHEROMOSA'],
		species['SPECIES_XURKITREE'],
		species['SPECIES_CELESTEELA'],
		species['SPECIES_KARTANA'],
		species['SPECIES_GUZZLORD'],
		species['SPECIES_NECROZMA'],
		species['SPECIES_MAGEARNA'],
		species['SPECIES_MARSHADOW'],
		species['SPECIES_POIPOLE'],
		species['SPECIES_NAGANADEL'],
		species['SPECIES_STAKATAKA'],
		species['SPECIES_BLACEPHALON'],
		species['SPECIES_ZERAORA'],
		species['SPECIES_MELTAN'],
		species['SPECIES_MELMETAL'],
		species['SPECIES_RATTATA_ALOLAN'],
		species['SPECIES_RATICATE_ALOLAN'],
		species['SPECIES_RAICHU_ALOLAN'],
		species['SPECIES_SANDSHREW_ALOLAN'],
		species['SPECIES_SANDSLASH_ALOLAN'],
		species['SPECIES_VULPIX_ALOLAN'],
		species['SPECIES_NINETALES_ALOLAN'],
		species['SPECIES_DIGLETT_ALOLAN'],
		species['SPECIES_DUGTRIO_ALOLAN'],
		species['SPECIES_MEOWTH_ALOLAN'],
		species['SPECIES_PERSIAN_ALOLAN'],
		species['SPECIES_GEODUDE_ALOLAN'],
		species['SPECIES_GRAVELER_ALOLAN'],
		species['SPECIES_GOLEM_ALOLAN'],
		species['SPECIES_GRIMER_ALOLAN'],
		species['SPECIES_MUK_ALOLAN'],
		species['SPECIES_EXEGGUTOR_ALOLAN'],
		species['SPECIES_MAROWAK_ALOLAN'],
		species['SPECIES_PIKACHU_COSPLAY'],
		species['SPECIES_PIKACHU_ROCK_STAR'],
		species['SPECIES_PIKACHU_BELLE'],
		species['SPECIES_PIKACHU_POP_STAR'],
		species['SPECIES_PIKACHU_PH_D'],
		species['SPECIES_PIKACHU_LIBRE'],
		species['SPECIES_PIKACHU_ORIGINAL_CAP'],
		species['SPECIES_PIKACHU_HOENN_CAP'],
		species['SPECIES_PIKACHU_SINNOH_CAP'],
		species['SPECIES_PIKACHU_UNOVA_CAP'],
		species['SPECIES_PIKACHU_KALOS_CAP'],
		species['SPECIES_PIKACHU_ALOLA_CAP'],
		species['SPECIES_PIKACHU_PARTNER_CAP'],
		species['SPECIES_PIKACHU_WORLD_CAP'],
		species['SPECIES_PICHU_SPIKY_EARED'],
		species['SPECIES_UNOWN_B'],
		species['SPECIES_UNOWN_C'],
		species['SPECIES_UNOWN_D'],
		species['SPECIES_UNOWN_E'],
		species['SPECIES_UNOWN_F'],
		species['SPECIES_UNOWN_G'],
		species['SPECIES_UNOWN_H'],
		species['SPECIES_UNOWN_I'],
		species['SPECIES_UNOWN_J'],
		species['SPECIES_UNOWN_K'],
		species['SPECIES_UNOWN_L'],
		species['SPECIES_UNOWN_M'],
		species['SPECIES_UNOWN_N'],
		species['SPECIES_UNOWN_O'],
		species['SPECIES_UNOWN_P'],
		species['SPECIES_UNOWN_Q'],
		species['SPECIES_UNOWN_R'],
		species['SPECIES_UNOWN_S'],
		species['SPECIES_UNOWN_T'],
		species['SPECIES_UNOWN_U'],
		species['SPECIES_UNOWN_V'],
		species['SPECIES_UNOWN_W'],
		species['SPECIES_UNOWN_X'],
		species['SPECIES_UNOWN_Y'],
		species['SPECIES_UNOWN_Z'],
		species['SPECIES_UNOWN_EMARK'],
		species['SPECIES_UNOWN_QMARK'],
		species['SPECIES_DEOXYS_ATTACK'],
		species['SPECIES_DEOXYS_DEFENSE'],
		species['SPECIES_DEOXYS_SPEED'],
		species['SPECIES_SHELLOS_EAST_SEA'],
		species['SPECIES_GASTRODON_EAST_SEA'],
		species['SPECIES_BASCULIN_BLUE_STRIPED'],
		species['SPECIES_DEERLING_SUMMER'],
		species['SPECIES_DEERLING_AUTUMN'],
		species['SPECIES_DEERLING_WINTER'],
		species['SPECIES_SAWSBUCK_SUMMER'],
		species['SPECIES_SAWSBUCK_AUTUMN'],
		species['SPECIES_SAWSBUCK_WINTER'],
		species['SPECIES_TORNADUS_THERIAN'],
		species['SPECIES_THUNDURUS_THERIAN'],
		species['SPECIES_LANDORUS_THERIAN'],
		species['SPECIES_ROTOM_HEAT'],
		species['SPECIES_ROTOM_WASH'],
		species['SPECIES_ROTOM_FROST'],
		species['SPECIES_ROTOM_FAN'],
		species['SPECIES_ROTOM_MOW'],
		species['SPECIES_GIRATINA_ORIGIN'],
		species['SPECIES_SHAYMIN_SKY'],
		species['SPECIES_KELDEO_RESOLUTE'],
		species['SPECIES_MELOETTA_PIROUETTE'],
		species['SPECIES_GRENINJA_BATTLE_BOND'],
		species['SPECIES_VIVILLON_POLAR'],
		species['SPECIES_VIVILLON_TUNDRA'],
		species['SPECIES_VIVILLON_CONTINENTAL'],
		species['SPECIES_VIVILLON_GARDEN'],
		species['SPECIES_VIVILLON_ELEGANT'],
		species['SPECIES_VIVILLON_MEADOW'],
		species['SPECIES_VIVILLON_MODERN'],
		species['SPECIES_VIVILLON_MARINE'],
		species['SPECIES_VIVILLON_ARCHIPELAGO'],
		species['SPECIES_VIVILLON_HIGH_PLAINS'],
		species['SPECIES_VIVILLON_SANDSTORM'],
		species['SPECIES_VIVILLON_RIVER'],
		species['SPECIES_VIVILLON_MONSOON'],
		species['SPECIES_VIVILLON_SAVANNA'],
		species['SPECIES_VIVILLON_SUN'],
		species['SPECIES_VIVILLON_OCEAN'],
		species['SPECIES_VIVILLON_JUNGLE'],
		species['SPECIES_VIVILLON_FANCY'],
		species['SPECIES_VIVILLON_POKE_BALL'],
		species['SPECIES_FLABEBE_YELLOW_FLOWER'],
		species['SPECIES_FLABEBE_ORANGE_FLOWER'],
		species['SPECIES_FLABEBE_BLUE_FLOWER'],
		species['SPECIES_FLABEBE_WHITE_FLOWER'],
		species['SPECIES_FLOETTE_YELLOW_FLOWER'],
		species['SPECIES_FLOETTE_ORANGE_FLOWER'],
		species['SPECIES_FLOETTE_BLUE_FLOWER'],
		species['SPECIES_FLOETTE_WHITE_FLOWER'],
		species['SPECIES_FLORGES_YELLOW_FLOWER'],
		species['SPECIES_FLORGES_ORANGE_FLOWER'],
		species['SPECIES_FLORGES_BLUE_FLOWER'],
		species['SPECIES_FLORGES_WHITE_FLOWER'],
		species['SPECIES_FURFROU_HEART_TRIM'],
		species['SPECIES_FURFROU_STAR_TRIM'],
		species['SPECIES_FURFROU_DIAMOND_TRIM'],
		species['SPECIES_FURFROU_DEBUTANTE_TRIM'],
		species['SPECIES_FURFROU_MATRON_TRIM'],
		species['SPECIES_FURFROU_DANDY_TRIM'],
		species['SPECIES_FURFROU_LA_REINE_TRIM'],
		species['SPECIES_FURFROU_KABUKI_TRIM'],
		species['SPECIES_FURFROU_PHARAOH_TRIM'],
		species['SPECIES_MEOWSTIC_FEMALE'],
		species['SPECIES_PUMPKABOO_SMALL'],
		species['SPECIES_PUMPKABOO_LARGE'],
		species['SPECIES_PUMPKABOO_SUPER'],
		species['SPECIES_GOURGEIST_SMALL'],
		species['SPECIES_GOURGEIST_LARGE'],
		species['SPECIES_GOURGEIST_SUPER'],
		species['SPECIES_ORICORIO_POM_POM'],
		species['SPECIES_ORICORIO_PAU'],
		species['SPECIES_ORICORIO_SENSU'],
		species['SPECIES_ROCKRUFF_OWN_TEMPO'],
		species['SPECIES_LYCANROC_MIDNIGHT'],
		species['SPECIES_LYCANROC_DUSK'],
		species['SPECIES_MINIOR_METEOR_ORANGE'],
		species['SPECIES_MINIOR_METEOR_YELLOW'],
		species['SPECIES_MINIOR_METEOR_GREEN'],
		species['SPECIES_MINIOR_METEOR_BLUE'],
		species['SPECIES_MINIOR_METEOR_INDIGO'],
		species['SPECIES_MINIOR_METEOR_VIOLET'],
		species['SPECIES_MAGEARNA_ORIGINAL_COLOR']
		]

items_held_gift = {
		species['SPECIES_BULBASAUR']: ([items['ITEM_VENUSAURITE']],None),
		species['SPECIES_IVYSAUR']: ([items['ITEM_VENUSAURITE']],None),
		species['SPECIES_VENUSAUR']: ([items['ITEM_VENUSAURITE']],None),
		species['SPECIES_CHARMANDER']: ([items['ITEM_CHARIZARDITE_Y']],items['ITEM_CHARIZARDITE_X']),
		species['SPECIES_CHARMELEON']: ([items['ITEM_CHARIZARDITE_Y']],items['ITEM_CHARIZARDITE_X']),
		species['SPECIES_CHARIZARD']: ([items['ITEM_CHARIZARDITE_Y']],items['ITEM_CHARIZARDITE_X']),
		species['SPECIES_SQUIRTLE']: ([items['ITEM_BLASTOISINITE']],None),
		species['SPECIES_WARTORTLE']: ([items['ITEM_BLASTOISINITE']],None),
		species['SPECIES_BLASTOISE']: ([items['ITEM_BLASTOISINITE']],None),
		species['SPECIES_WEEDLE']: ([items['ITEM_BEEDRILLITE']],None),
		species['SPECIES_KAKUNA']: ([items['ITEM_BEEDRILLITE']],None),
		species['SPECIES_BEEDRILL']: ([items['ITEM_BEEDRILLITE']],None),
		species['SPECIES_PIDGEY']: ([items['ITEM_PIDGEOTITE']],None),
		species['SPECIES_PIDGEOTTO']: ([items['ITEM_PIDGEOTITE']],None),
		species['SPECIES_PIDGEOT']: ([items['ITEM_PIDGEOTITE']],None),
		species['SPECIES_ABRA']: ([items['ITEM_ALAKAZITE']],None),
		species['SPECIES_KADABRA']: ([items['ITEM_ALAKAZITE']],None),
		species['SPECIES_ALAKAZAM']: ([items['ITEM_ALAKAZITE']],None),
		species['SPECIES_SLOWPOKE']: ([items['ITEM_SLOWBRONITE']],None),
		species['SPECIES_SLOWBRO']: ([items['ITEM_SLOWBRONITE']],None),
		species['SPECIES_GASTLY']: ([items['ITEM_GENGARITE']],None),
		species['SPECIES_HAUNTER']: ([items['ITEM_GENGARITE']],None),
		species['SPECIES_GENGAR']: ([items['ITEM_GENGARITE']],None),
		species['SPECIES_KANGASKHAN']: ([items['ITEM_KANGASKHANITE']],None),
		species['SPECIES_PINSIR']: ([items['ITEM_PINSIRITE']],None),
		species['SPECIES_MAGIKARP']: ([items['ITEM_GYARADOSITE']],None),
		species['SPECIES_GYARADOS']: ([items['ITEM_GYARADOSITE']],None),
		species['SPECIES_AERODACTYL']: ([items['ITEM_AERODACTYLITE']],None),
		species['SPECIES_MEWTWO']: ([items['ITEM_MEWTWONITE_Y']],items['ITEM_MEWTWONITE_X']),
		species['SPECIES_MAREEP']: ([items['ITEM_AMPHAROSITE']],None),
		species['SPECIES_FLAAFFY']: ([items['ITEM_AMPHAROSITE']],None),
		species['SPECIES_AMPHAROS']: ([items['ITEM_AMPHAROSITE']],None),
		species['SPECIES_ONIX']: ([items['ITEM_STEELIXITE']],None),
		species['SPECIES_STEELIX']: ([items['ITEM_STEELIXITE']],None),
		species['SPECIES_SCYTHER']: ([items['ITEM_SCIZORITE']],None),
		species['SPECIES_SCIZOR']: ([items['ITEM_SCIZORITE']],None),
		species['SPECIES_HERACROSS']: ([items['ITEM_HERACRONITE']],None),
		species['SPECIES_HOUNDOUR']: ([items['ITEM_HOUNDOOMINITE']],None),
		species['SPECIES_HOUNDOOM']: ([items['ITEM_HOUNDOOMINITE']],None),
		species['SPECIES_LARVITAR']: ([items['ITEM_TYRANITARITE']],None),
		species['SPECIES_PUPITAR']: ([items['ITEM_TYRANITARITE']],None),
		species['SPECIES_TYRANITAR']: ([items['ITEM_TYRANITARITE']],None),
		species['SPECIES_TREECKO']: ([items['ITEM_SCEPTILITE']],None),
		species['SPECIES_GROVYLE']: ([items['ITEM_SCEPTILITE']],None),
		species['SPECIES_SCEPTILE']: ([items['ITEM_SCEPTILITE']],None),
		species['SPECIES_TORCHIC']: ([items['ITEM_BLAZIKENITE']],None),
		species['SPECIES_COMBUSKEN']: ([items['ITEM_BLAZIKENITE']],None),
		species['SPECIES_BLAZIKEN']: ([items['ITEM_BLAZIKENITE']],None),
		species['SPECIES_MUDKIP']: ([items['ITEM_SWAMPERTITE']],None),
		species['SPECIES_MARSHTOMP']: ([items['ITEM_SWAMPERTITE']],None),
		species['SPECIES_SWAMPERT']: ([items['ITEM_SWAMPERTITE']],None),
		species['SPECIES_SABLEYE']: ([items['ITEM_SABLENITE']],None),
		species['SPECIES_MAWILE']: ([items['ITEM_MAWILITE']],None),
		species['SPECIES_ARON']: ([items['ITEM_AGGRONITE']],None),
		species['SPECIES_LAIRON']: ([items['ITEM_AGGRONITE']],None),
		species['SPECIES_AGGRON']: ([items['ITEM_AGGRONITE']],None),
		species['SPECIES_MEDITITE']: ([items['ITEM_MEDICHAMITE']],None),
		species['SPECIES_MEDICHAM']: ([items['ITEM_MEDICHAMITE']],None),
		species['SPECIES_ELECTRIKE']: ([items['ITEM_MANECTITE']],None),
		species['SPECIES_MANECTRIC']: ([items['ITEM_MANECTITE']],None),
		species['SPECIES_CARVANHA']: ([items['ITEM_SHARPEDONITE']],None),
		species['SPECIES_SHARPEDO']: ([items['ITEM_SHARPEDONITE']],None),
		species['SPECIES_NUMEL']: ([items['ITEM_CAMERUPTITE']],None),
		species['SPECIES_CAMERUPT']: ([items['ITEM_CAMERUPTITE']],None),
		species['SPECIES_ABSOL']: ([items['ITEM_ABSOLITE']],None),
		species['SPECIES_SHUPPET']: ([items['ITEM_BANETTITE']],None),
		species['SPECIES_BANETTE']: ([items['ITEM_BANETTITE']],None),
		species['SPECIES_SNORUNT']: ([items['ITEM_GLALITITE']],None),
		species['SPECIES_GLALIE']: ([items['ITEM_GLALITITE']],None),
		species['SPECIES_SWABLU']: ([items['ITEM_ALTARIANITE']],None),
		species['SPECIES_ALTARIA']: ([items['ITEM_ALTARIANITE']],None),
		species['SPECIES_RALTS']: ([items['ITEM_GARDEVOIRITE']],None),
		species['SPECIES_KIRLIA']: ([items['ITEM_GARDEVOIRITE']],items['ITEM_GALLADITE']),
		species['SPECIES_GARDEVOIR']: ([items['ITEM_GARDEVOIRITE']],None),
		species['SPECIES_GALLADE']: ([items['ITEM_GALLADITE']],None),
		species['SPECIES_BAGON']: ([items['ITEM_SALAMENCITE']],None),
		species['SPECIES_SHELGON']: ([items['ITEM_SALAMENCITE']],None),
		species['SPECIES_SALAMENCE']: ([items['ITEM_SALAMENCITE']],None),
		species['SPECIES_BELDUM']: ([items['ITEM_METAGROSSITE']],None),
		species['SPECIES_METANG']: ([items['ITEM_METAGROSSITE']],None),
		species['SPECIES_METAGROSS']: ([items['ITEM_METAGROSSITE']],None),
		species['SPECIES_LATIOS']: ([items['ITEM_LATIOSITE']],None),
		species['SPECIES_LATIAS']: ([items['ITEM_LATIASITE']],None),
		species['SPECIES_BUNEARY']: ([items['ITEM_LOPUNNITE']],None),
		species['SPECIES_LOPUNNY']: ([items['ITEM_LOPUNNITE']],None),
		species['SPECIES_GIBLE']: ([items['ITEM_GARCHOMPITE']],None),
		species['SPECIES_GABITE']: ([items['ITEM_GARCHOMPITE']],None),
		species['SPECIES_GARCHOMP']: ([items['ITEM_GARCHOMPITE']],None),
		species['SPECIES_RIOLU']: ([items['ITEM_LUCARIONITE']],None),
		species['SPECIES_LUCARIO']: ([items['ITEM_LUCARIONITE']],None),
		species['SPECIES_SNOVER']: ([items['ITEM_ABOMASITE']],None),
		species['SPECIES_ABOMASNOW']: ([items['ITEM_ABOMASITE']],None),
		species['SPECIES_AUDINO']: ([items['ITEM_AUDINITE']],None),
		species['SPECIES_DIANCIE']: ([items['ITEM_DIANCITE']],None),
		species['SPECIES_ARCEUS']: ([items['ITEM_INSECT_PLATE'], items['ITEM_DREAD_PLATE'], items['ITEM_DRACO_PLATE'], items['ITEM_ZAP_PLATE'], items['ITEM_PIXIE_PLATE'], items['ITEM_FIST_PLATE'], items['ITEM_FLAME_PLATE'], items['ITEM_SKY_PLATE'], items['ITEM_SPOOKY_PLATE'], items['ITEM_MEADOW_PLATE'], items['ITEM_EARTH_PLATE'], items['ITEM_ICICLE_PLATE'], items['ITEM_TOXIC_PLATE'], items['ITEM_MIND_PLATE'], items['ITEM_STONE_PLATE'], items['ITEM_IRON_PLATE'], items['ITEM_SPLASH_PLATE']],None),
		species['SPECIES_TYPE_NULL']: ([items['ITEM_BUG_MEMORY'], items['ITEM_DARK_MEMORY'], items['ITEM_DRAGON_MEMORY'], items['ITEM_ELECTRIC_MEMORY'], items['ITEM_FAIRY_MEMORY'], items['ITEM_FIGHTING_MEMORY'], items['ITEM_FIRE_MEMORY'], items['ITEM_FLYING_MEMORY'], items['ITEM_GHOST_MEMORY'], items['ITEM_GRASS_MEMORY'], items['ITEM_GROUND_MEMORY'], items['ITEM_ICE_MEMORY'], items['ITEM_POISON_MEMORY'], items['ITEM_PSYCHIC_MEMORY'], items['ITEM_ROCK_MEMORY'], items['ITEM_STEEL_MEMORY'], items['ITEM_WATER_MEMORY']],None),
		species['SPECIES_SILVALLY']: ([items['ITEM_BUG_MEMORY'], items['ITEM_DARK_MEMORY'], items['ITEM_DRAGON_MEMORY'], items['ITEM_ELECTRIC_MEMORY'], items['ITEM_FAIRY_MEMORY'], items['ITEM_FIGHTING_MEMORY'], items['ITEM_FIRE_MEMORY'], items['ITEM_FLYING_MEMORY'], items['ITEM_GHOST_MEMORY'], items['ITEM_GRASS_MEMORY'], items['ITEM_GROUND_MEMORY'], items['ITEM_ICE_MEMORY'], items['ITEM_POISON_MEMORY'], items['ITEM_PSYCHIC_MEMORY'], items['ITEM_ROCK_MEMORY'], items['ITEM_STEEL_MEMORY'], items['ITEM_WATER_MEMORY']],None),
		species['SPECIES_GENESECT']: ([items['ITEM_DOUSE_DRIVE'], items['ITEM_SHOCK_DRIVE'], items['ITEM_BURN_DRIVE'], items['ITEM_CHILL_DRIVE']], None),
		species['SPECIES_RAICHU_ALOLAN']: ([items['ITEM_ALORAICHIUM_Z']],None),
		species['SPECIES_ROWLET']: ([items['ITEM_DECIDIUM_Z']],None),
		species['SPECIES_DARTRIX']: ([items['ITEM_DECIDIUM_Z']],None),
		species['SPECIES_DECIDUEYE']: ([items['ITEM_DECIDIUM_Z']],None),
		species['SPECIES_EEVEE']: ([items['ITEM_EEVIUM_Z']],None),
		species['SPECIES_LITTEN']: ([items['ITEM_INCINIUM_Z']],None),
		species['SPECIES_TORRACAT']: ([items['ITEM_INCINIUM_Z']],None),
		species['SPECIES_INCINEROAR']: ([items['ITEM_INCINIUM_Z']],None),
		species['SPECIES_KOMMO_O']: ([items['ITEM_KOMMONIUM_Z']],None),
		species['SPECIES_LUNALA']: ([items['ITEM_LUNALIUM_Z']],None),
		species['SPECIES_ROCKRUFF']: ([items['ITEM_LYCANIUM_Z']],None),
		species['SPECIES_ROCKRUFF_OWN_TEMPO']: ([items['ITEM_LYCANIUM_Z']],None),
		species['SPECIES_LYCANROC']: ([items['ITEM_LYCANIUM_Z']],None),
		species['SPECIES_LYCANROC_DUSK']: ([items['ITEM_LYCANIUM_Z']],None),
		species['SPECIES_LYCANROC_MIDNIGHT']: ([items['ITEM_LYCANIUM_Z']],None),
		species['SPECIES_MARSHADOW']: ([items['ITEM_MARSHADIUM_Z']],None),
		species['SPECIES_MEW']: ([items['ITEM_MEWNIUM_Z']],items['ITEM_LUM_BERRY']),
		species['SPECIES_MIMIKYU']: ([items['ITEM_MIMIKIUM_Z']],None),
		species['SPECIES_PIKACHU']: ([items['ITEM_PIKANIUM_Z']],None),
		species['SPECIES_PIKACHU_ORIGINAL_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_HOENN_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_SINNOH_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_UNOVA_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_KALOS_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_ALOLA_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_PARTNER_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_WORLD_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_POPPLIO']: ([items['ITEM_PRIMARIUM_Z']],None),
		species['SPECIES_BRIONNE']: ([items['ITEM_PRIMARIUM_Z']],None),
		species['SPECIES_PRIMARINA']: ([items['ITEM_PRIMARIUM_Z']],None),
		species['SPECIES_MUNCHLAX']: ([items['ITEM_SNORLIUM_Z']],None),
		species['SPECIES_SNORLAX']: ([items['ITEM_SNORLIUM_Z']],None),
		species['SPECIES_SOLGALEO']: ([items['ITEM_SOLGANIUM_Z']],None),
		species['SPECIES_TAPU_FINI']: ([items['ITEM_TAPUNIUM_Z']],None),
		species['SPECIES_TAPU_BULU']: ([items['ITEM_TAPUNIUM_Z']],None),
		species['SPECIES_TAPU_LELE']: ([items['ITEM_TAPUNIUM_Z']],None),
		species['SPECIES_TAPU_KOKO']: ([items['ITEM_TAPUNIUM_Z']],None),
		species['SPECIES_NECROZMA']: ([items['ITEM_ULTRANECROZIUM_Z']],None),
		}

items_foe_held = {
		species['SPECIES_VENUSAUR']: ([items['ITEM_VENUSAURITE']],None),
		species['SPECIES_CHARIZARD']: ([items['ITEM_CHARIZARDITE_Y']],items['ITEM_CHARIZARDITE_X']),
		species['SPECIES_BLASTOISE']: ([items['ITEM_BLASTOISINITE']],None),
		species['SPECIES_BEEDRILL']: ([items['ITEM_BEEDRILLITE']],None),
		species['SPECIES_PIDGEOT']: ([items['ITEM_PIDGEOTITE']],None),
		species['SPECIES_ALAKAZAM']: ([items['ITEM_ALAKAZITE']],None),
		species['SPECIES_SLOWBRO']: ([items['ITEM_SLOWBRONITE']],None),
		species['SPECIES_GENGAR']: ([items['ITEM_GENGARITE']],None),
		species['SPECIES_KANGASKHAN']: ([items['ITEM_KANGASKHANITE']],None),
		species['SPECIES_PINSIR']: ([items['ITEM_PINSIRITE']],None),
		species['SPECIES_GYARADOS']: ([items['ITEM_GYARADOSITE']],None),
		species['SPECIES_AERODACTYL']: ([items['ITEM_AERODACTYLITE']],None),
		species['SPECIES_MEWTWO']: ([items['ITEM_MEWTWONITE_Y']],items['ITEM_MEWTWONITE_X']),
		species['SPECIES_AMPHAROS']: ([items['ITEM_AMPHAROSITE']],None),
		species['SPECIES_STEELIX']: ([items['ITEM_STEELIXITE']],None),
		species['SPECIES_SCIZOR']: ([items['ITEM_SCIZORITE']],None),
		species['SPECIES_HERACROSS']: ([items['ITEM_HERACRONITE']],None),
		species['SPECIES_HOUNDOOM']: ([items['ITEM_HOUNDOOMINITE']],None),
		species['SPECIES_TYRANITAR']: ([items['ITEM_TYRANITARITE']],None),
		species['SPECIES_SCEPTILE']: ([items['ITEM_SCEPTILITE']],None),
		species['SPECIES_BLAZIKEN']: ([items['ITEM_BLAZIKENITE']],None),
		species['SPECIES_SWAMPERT']: ([items['ITEM_SWAMPERTITE']],None),
		species['SPECIES_SABLEYE']: ([items['ITEM_SABLENITE']],None),
		species['SPECIES_MAWILE']: ([items['ITEM_MAWILITE']],None),
		species['SPECIES_AGGRON']: ([items['ITEM_AGGRONITE']],None),
		species['SPECIES_MEDICHAM']: ([items['ITEM_MEDICHAMITE']],None),
		species['SPECIES_MANECTRIC']: ([items['ITEM_MANECTITE']],None),
		species['SPECIES_SHARPEDO']: ([items['ITEM_SHARPEDONITE']],None),
		species['SPECIES_CAMERUPT']: ([items['ITEM_CAMERUPTITE']],None),
		species['SPECIES_ABSOL']: ([items['ITEM_ABSOLITE']],None),
		species['SPECIES_BANETTE']: ([items['ITEM_BANETTITE']],None),
		species['SPECIES_GLALIE']: ([items['ITEM_GLALITITE']],None),
		species['SPECIES_ALTARIA']: ([items['ITEM_ALTARIANITE']],None),
		species['SPECIES_GARDEVOIR']: ([items['ITEM_GARDEVOIRITE']],None),
		species['SPECIES_GALLADE']: ([items['ITEM_GALLADITE']],None),
		species['SPECIES_SALAMENCE']: ([items['ITEM_SALAMENCITE']],None),
		species['SPECIES_METAGROSS']: ([items['ITEM_METAGROSSITE']],None),
		species['SPECIES_LATIOS']: ([items['ITEM_LATIOSITE']],items['ITEM_SOUL_DEW']),
		species['SPECIES_LATIAS']: ([items['ITEM_LATIASITE']],items['ITEM_SOUL_DEW']),
		species['SPECIES_LOPUNNY']: ([items['ITEM_LOPUNNITE']],None),
		species['SPECIES_GARCHOMP']: ([items['ITEM_GARCHOMPITE']],None),
		species['SPECIES_LUCARIO']: ([items['ITEM_LUCARIONITE']],None),
		species['SPECIES_ABOMASNOW']: ([items['ITEM_ABOMASITE']],None),
		species['SPECIES_AUDINO']: ([items['ITEM_AUDINITE']],None),
		species['SPECIES_DIANCIE']: ([items['ITEM_DIANCITE']],None),
		species['SPECIES_DIANCIE']: ([items['ITEM_DIANCITE']],None),
		species['SPECIES_ARCEUS']: ([items['ITEM_INSECT_PLATE'], items['ITEM_DREAD_PLATE'], items['ITEM_DRACO_PLATE'], items['ITEM_ZAP_PLATE'], items['ITEM_PIXIE_PLATE'], items['ITEM_FIST_PLATE'], items['ITEM_FLAME_PLATE'], items['ITEM_SKY_PLATE'], items['ITEM_SPOOKY_PLATE'], items['ITEM_MEADOW_PLATE'], items['ITEM_EARTH_PLATE'], items['ITEM_ICICLE_PLATE'], items['ITEM_TOXIC_PLATE'], items['ITEM_MIND_PLATE'], items['ITEM_STONE_PLATE'], items['ITEM_IRON_PLATE'], items['ITEM_SPLASH_PLATE']],None),
		species['SPECIES_SILVALLY']: ([items['ITEM_BUG_MEMORY'], items['ITEM_DARK_MEMORY'], items['ITEM_DRAGON_MEMORY'], items['ITEM_ELECTRIC_MEMORY'], items['ITEM_FAIRY_MEMORY'], items['ITEM_FIGHTING_MEMORY'], items['ITEM_FIRE_MEMORY'], items['ITEM_FLYING_MEMORY'], items['ITEM_GHOST_MEMORY'], items['ITEM_GRASS_MEMORY'], items['ITEM_GROUND_MEMORY'], items['ITEM_ICE_MEMORY'], items['ITEM_POISON_MEMORY'], items['ITEM_PSYCHIC_MEMORY'], items['ITEM_ROCK_MEMORY'], items['ITEM_STEEL_MEMORY'], items['ITEM_WATER_MEMORY']],None),
		species['SPECIES_GENESECT']: ([items['ITEM_DOUSE_DRIVE'], items['ITEM_SHOCK_DRIVE'], items['ITEM_BURN_DRIVE'], items['ITEM_CHILL_DRIVE']], None),
		species['SPECIES_RAICHU_ALOLAN']: ([items['ITEM_ALORAICHIUM_Z']],None),
		species['SPECIES_DECIDUEYE']: ([items['ITEM_DECIDIUM_Z']],None),
		species['SPECIES_EEVEE']: ([items['ITEM_EEVIUM_Z']],None),
		species['SPECIES_INCINEROAR']: ([items['ITEM_INCINIUM_Z']],None),
		species['SPECIES_KOMMO_O']: ([items['ITEM_KOMMONIUM_Z']],None),
		species['SPECIES_LUNALA']: ([items['ITEM_LUNALIUM_Z']],None),
		species['SPECIES_LYCANROC']: ([items['ITEM_LYCANIUM_Z']],None),
		species['SPECIES_LYCANROC_DUSK']: ([items['ITEM_LYCANIUM_Z']],None),
		species['SPECIES_LYCANROC_MIDNIGHT']: ([items['ITEM_LYCANIUM_Z']],None),
		species['SPECIES_MARSHADOW']: ([items['ITEM_MARSHADIUM_Z']],None),
		species['SPECIES_MEW']: ([items['ITEM_MEWNIUM_Z']],None),
		species['SPECIES_MIMIKYU']: ([items['ITEM_MIMIKIUM_Z']],None),
		species['SPECIES_PIKACHU']: ([items['ITEM_PIKANIUM_Z']],None),
		species['SPECIES_PIKACHU_ORIGINAL_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_HOENN_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_SINNOH_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_UNOVA_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_KALOS_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_ALOLA_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_PARTNER_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PIKACHU_WORLD_CAP']: ([items['ITEM_PIKASHUNIUM_Z']],None),
		species['SPECIES_PRIMARINA']: ([items['ITEM_PRIMARIUM_Z']],None),
		species['SPECIES_SNORLAX']: ([items['ITEM_SNORLIUM_Z']],None),
		species['SPECIES_SOLGALEO']: ([items['ITEM_SOLGANIUM_Z']],None),
		species['SPECIES_TAPU_FINI']: ([items['ITEM_TAPUNIUM_Z']],None),
		species['SPECIES_TAPU_BULU']: ([items['ITEM_TAPUNIUM_Z']],None),
		species['SPECIES_TAPU_LELE']: ([items['ITEM_TAPUNIUM_Z']],None),
		species['SPECIES_TAPU_KOKO']: ([items['ITEM_TAPUNIUM_Z']],None),
		species['SPECIES_NECROZMA']: ([items['ITEM_ULTRANECROZIUM_Z']],None),
		}

items_any_held = [
		items['ITEM_BRIGHT_POWDER'],
		items['ITEM_WHITE_HERB'],
		items['ITEM_QUICK_CLAW'],
		items['ITEM_SOOTHE_BELL'],
		items['ITEM_MENTAL_HERB'],
		items['ITEM_CHOICE_BAND'],
		items['ITEM_SILVER_POWDER'],
		items['ITEM_CLEANSE_TAG'],
		items['ITEM_SMOKE_BALL'],
		items['ITEM_SCOPE_LENS'],
		items['ITEM_LEFTOVERS'],
		items['ITEM_LIGHT_BALL'],
		items['ITEM_SOFT_SAND'],
		items['ITEM_HARD_STONE'],
		items['ITEM_MIRACLE_SEED'],
		items['ITEM_BLACK_GLASSES'],
		items['ITEM_BLACK_BELT'],
		items['ITEM_MAGNET'],
		items['ITEM_MYSTIC_WATER'],
		items['ITEM_SHARP_BEAK'],
		items['ITEM_POISON_BARB'],
		items['ITEM_NEVER_MELT_ICE'],
		items['ITEM_SPELL_TAG'],
		items['ITEM_TWISTED_SPOON'],
		items['ITEM_CHARCOAL'],
		items['ITEM_DRAGON_FANG'],
		items['ITEM_SILK_SCARF'],
		items['ITEM_SHELL_BELL'],
		items['ITEM_CHOICE_SCARF'],
		items['ITEM_CHOICE_SPECS'],
		items['ITEM_FOCUS_SASH'],
		items['ITEM_WIDE_LENS'],
		items['ITEM_ZOOM_LENS'],
		items['ITEM_METRONOME'],
		items['ITEM_MUSCLE_BAND'],
		items['ITEM_WISE_GLASSES'],
		items['ITEM_EXPERT_BELT'],
		items['ITEM_LIGHT_CLAY'],
		items['ITEM_ICY_ROCK'],
		items['ITEM_SMOOTH_ROCK'],
		items['ITEM_HEAT_ROCK'],
		items['ITEM_DAMP_ROCK'],
		items['ITEM_GRIP_CLAW'],
		items['ITEM_LIFE_ORB'],
		items['ITEM_TOXIC_ORB'],
		items['ITEM_FLAME_ORB'],
		items['ITEM_STICKY_BARB'],
		items['ITEM_BLACK_SLUDGE'],
		items['ITEM_IRON_BALL'],
		items['ITEM_LAGGING_TAIL'],
		items['ITEM_SHED_SHELL'],
		items['ITEM_BIG_ROOT'],
		items['ITEM_EVIOLITE'],
		items['ITEM_FLOAT_STONE'],
		items['ITEM_ROCKY_HELMET'],
		items['ITEM_AIR_BALLOON'],
		items['ITEM_RED_CARD'],
		items['ITEM_RING_TARGET'],
		items['ITEM_BINDING_BAND'],
		items['ITEM_EJECT_BUTTON'],
		items['ITEM_ABSORB_BULB'],
		items['ITEM_CELL_BATTERY'],
		items['ITEM_LUMINOUS_MOSS'],
		items['ITEM_SNOWBALL'],
		items['ITEM_WEAKNESS_POLICY'],
		items['ITEM_ASSAULT_VEST'],
		items['ITEM_SAFETY_GOGGLES'],
		items['ITEM_ADRENALINE_ORB'],
		items['ITEM_TERRAIN_EXTENDER'],
		items['ITEM_PROTECTIVE_PADS'],
		items['ITEM_ELECTRIC_SEED'],
		items['ITEM_PSYCHIC_SEED'],
		items['ITEM_MISTY_SEED'],
		items['ITEM_GRASSY_SEED'],
		items['ITEM_SEA_INCENSE'],
		items['ITEM_LAX_INCENSE'],
		items['ITEM_ODD_INCENSE'],
		items['ITEM_ROCK_INCENSE'],
		items['ITEM_FULL_INCENSE'],
		items['ITEM_WAVE_INCENSE'],
		items['ITEM_ROSE_INCENSE'],
		items['ITEM_LUCK_INCENSE'],
		items['ITEM_PURE_INCENSE'],
		items['ITEM_METAL_COAT'],
		items['ITEM_DRAGON_SCALE'],
		items['ITEM_KINGS_ROCK'],
		items['ITEM_FOCUS_BAND'],
		items['ITEM_MACHO_BRACE']
		]

items_nonheld_nontm = [
		items['ITEM_MASTER_BALL'],
		items['ITEM_ULTRA_BALL'],
		items['ITEM_GREAT_BALL'],
		items['ITEM_POKE_BALL'],
		items['ITEM_SAFARI_BALL'],
		items['ITEM_NET_BALL'],
		items['ITEM_DIVE_BALL'],
		items['ITEM_NEST_BALL'],
		items['ITEM_REPEAT_BALL'],
		items['ITEM_TIMER_BALL'],
		items['ITEM_LUXURY_BALL'],
		items['ITEM_DUSK_BALL'],
		items['ITEM_HEAL_BALL'],
		items['ITEM_QUICK_BALL'],
		items['ITEM_CHERISH_BALL'],
		items['ITEM_FAST_BALL'],
		items['ITEM_LEVEL_BALL'],
		items['ITEM_LURE_BALL'],
		items['ITEM_HEAVY_BALL'],
		items['ITEM_LOVE_BALL'],
		items['ITEM_FRIEND_BALL'],
		items['ITEM_MOON_BALL'],
		items['ITEM_SPORT_BALL'],
		items['ITEM_PARK_BALL'],
		items['ITEM_DREAM_BALL'],
		items['ITEM_BEAST_BALL'],
		items['ITEM_PREMIER_BALL'],
		items['ITEM_POTION'],
		items['ITEM_ANTIDOTE'],
		items['ITEM_BURN_HEAL'],
		items['ITEM_ICE_HEAL'],
		items['ITEM_AWAKENING'],
		items['ITEM_PARALYZE_HEAL'],
		items['ITEM_FULL_RESTORE'],
		items['ITEM_MAX_POTION'],
		items['ITEM_HYPER_POTION'],
		items['ITEM_SUPER_POTION'],
		items['ITEM_FULL_HEAL'],
		items['ITEM_REVIVE'],
		items['ITEM_MAX_REVIVE'],
		items['ITEM_FRESH_WATER'],
		items['ITEM_SODA_POP'],
		items['ITEM_LEMONADE'],
		items['ITEM_MOOMOO_MILK'],
		items['ITEM_ENERGY_POWDER'],
		items['ITEM_ENERGY_ROOT'],
		items['ITEM_HEAL_POWDER'],
		items['ITEM_REVIVAL_HERB'],
		items['ITEM_ETHER'],
		items['ITEM_MAX_ETHER'],
		items['ITEM_ELIXIR'],
		items['ITEM_MAX_ELIXIR'],
		items['ITEM_LAVA_COOKIE'],
		items['ITEM_BLUE_FLUTE'],
		items['ITEM_YELLOW_FLUTE'],
		items['ITEM_RED_FLUTE'],
		items['ITEM_BLACK_FLUTE'],
		items['ITEM_WHITE_FLUTE'],
		items['ITEM_BERRY_JUICE'],
		items['ITEM_SWEET_HEART'],
		items['ITEM_BIG_MALASADA'],
		items['ITEM_OLD_GATEAU'],
		items['ITEM_SACRED_ASH'],
		items['ITEM_SHOAL_SALT'],
		items['ITEM_SHOAL_SHELL'],
		items['ITEM_RED_SHARD'],
		items['ITEM_BLUE_SHARD'],
		items['ITEM_YELLOW_SHARD'],
		items['ITEM_GREEN_SHARD'],
		items['ITEM_HP_UP'],
		items['ITEM_PROTEIN'],
		items['ITEM_IRON'],
		items['ITEM_CARBOS'],
		items['ITEM_CALCIUM'],
		items['ITEM_RARE_CANDY'],
		items['ITEM_PP_UP'],
		items['ITEM_ZINC'],
		items['ITEM_PP_MAX'],
		items['ITEM_GUARD_SPEC'],
		items['ITEM_DIRE_HIT'],
		items['ITEM_X_ATTACK'],
		items['ITEM_X_DEFENSE'],
		items['ITEM_X_SPEED'],
		items['ITEM_X_ACCURACY'],
		items['ITEM_X_SP_ATK'],
		items['ITEM_X_SP_DEF'],
		items['ITEM_POKE_DOLL'],
		items['ITEM_FLUFFY_TAIL'],
		items['ITEM_ESCAPE_ROPE'],
		items['ITEM_REPEL'],
		items['ITEM_SUPER_REPEL'],
		items['ITEM_MAX_REPEL'],
		items['ITEM_ABILITY_CAPSULE'],
		items['ITEM_HEALTH_WING'],
		items['ITEM_MUSCLE_WING'],
		items['ITEM_RESIST_WING'],
		items['ITEM_GENIUS_WING'],
		items['ITEM_CLEVER_WING'],
		items['ITEM_SWIFT_WING'],
		items['ITEM_PRETTY_WING'],
		items['ITEM_SUN_STONE'],
		items['ITEM_MOON_STONE'],
		items['ITEM_FIRE_STONE'],
		items['ITEM_THUNDER_STONE'],
		items['ITEM_WATER_STONE'],
		items['ITEM_LEAF_STONE'],
		items['ITEM_DAWN_STONE'],
		items['ITEM_DUSK_STONE'],
		items['ITEM_SHINY_STONE'],
		items['ITEM_ICE_STONE'],
		items['ITEM_TINY_MUSHROOM'],
		items['ITEM_BIG_MUSHROOM'],
		items['ITEM_PEARL'],
		items['ITEM_BIG_PEARL'],
		items['ITEM_STARDUST'],
		items['ITEM_STAR_PIECE'],
		items['ITEM_NUGGET'],
		items['ITEM_HEART_SCALE'],
		items['ITEM_RED_NECTAR'],
		items['ITEM_YELLOW_NECTAR'],
		items['ITEM_PINK_NECTAR'],
		items['ITEM_PURPLE_NECTAR'],
		items['ITEM_HONEY'],
		items['ITEM_RARE_BONE'],
		items['ITEM_AMULET_COIN'],
		items['ITEM_EVERSTONE'],
		items['ITEM_LUCKY_EGG'],
		items['ITEM_OVAL_STONE'],
		items['ITEM_PROTECTOR'],
		items['ITEM_ELECTIRIZER'],
		items['ITEM_MAGMARIZER'],
		items['ITEM_DUBIOUS_DISC'],
		items['ITEM_REAPER_CLOTH'],
		items['ITEM_RAZOR_CLAW'],
		items['ITEM_RAZOR_FANG'],
		items['ITEM_PRISM_SCALE'],
		items['ITEM_WHIPPED_DREAM'],
		items['ITEM_SACHET'],
		items['ITEM_UP_GRADE'],
		items['ITEM_POWER_BRACER'],
		items['ITEM_POWER_BELT'],
		items['ITEM_POWER_LENS'],
		items['ITEM_POWER_BAND'],
		items['ITEM_POWER_ANKLET'],
		items['ITEM_POWER_WEIGHT'],
		items['ITEM_POWER_HERB'],
		items['ITEM_DESTINY_KNOT'],
		items['ITEM_BUG_GEM'],
		items['ITEM_DARK_GEM'],
		items['ITEM_DRAGON_GEM'],
		items['ITEM_ELECTRIC_GEM'],
		items['ITEM_FAIRY_GEM'],
		items['ITEM_FIGHTING_GEM'],
		items['ITEM_FIRE_GEM'],
		items['ITEM_FLYING_GEM'],
		items['ITEM_GHOST_GEM'],
		items['ITEM_GRASS_GEM'],
		items['ITEM_GROUND_GEM'],
		items['ITEM_ICE_GEM'],
		items['ITEM_NORMAL_GEM'],
		items['ITEM_POISON_GEM'],
		items['ITEM_PSYCHIC_GEM'],
		items['ITEM_ROCK_GEM'],
		items['ITEM_STEEL_GEM'],
		items['ITEM_WATER_GEM'],
		items['ITEM_SOUL_DEW'],
		items['ITEM_DEEP_SEA_TOOTH'],
		items['ITEM_DEEP_SEA_SCALE'],
		items['ITEM_LUCKY_PUNCH'],
		items['ITEM_METAL_POWDER'],
		items['ITEM_THICK_CLUB'],
		items['ITEM_STICK'],
		items['ITEM_QUICK_POWDER'],
		items['ITEM_ODD_KEYSTONE'],
		items['ITEM_ADAMANT_ORB'],
		items['ITEM_LUSTROUS_ORB'],
		items['ITEM_GRISEOUS_ORB'],
		items['ITEM_GRACIDEA'],
		items['ITEM_RED_SCARF'],
		items['ITEM_BLUE_SCARF'],
		items['ITEM_PINK_SCARF'],
		items['ITEM_GREEN_SCARF'],
		items['ITEM_YELLOW_SCARF'],
		items['ITEM_OLD_AMBER'],
		items['ITEM_ARMOR_FOSSIL'],
		items['ITEM_SKULL_FOSSIL'],
		items['ITEM_HELIX_FOSSIL'],
		items['ITEM_DOME_FOSSIL'],
		items['ITEM_COVER_FOSSIL'],
		items['ITEM_PLUME_FOSSIL'],
		items['ITEM_JAW_FOSSIL'],
		items['ITEM_SAIL_FOSSIL'],
		items['ITEM_ROOT_FOSSIL'],
		items['ITEM_CLAW_FOSSIL'],
		items['ITEM_NORMALIUM_Z'],
		items['ITEM_FIGHTINIUM_Z'],
		items['ITEM_FLYINIUM_Z'],
		items['ITEM_POISONIUM_Z'],
		items['ITEM_GROUNDIUM_Z'],
		items['ITEM_ROCKIUM_Z'],
		items['ITEM_BUGINIUM_Z'],
		items['ITEM_GHOSTIUM_Z'],
		items['ITEM_STEELIUM_Z'],
		items['ITEM_FIRIUM_Z'],
		items['ITEM_WATERIUM_Z'],
		items['ITEM_GRASSIUM_Z'],
		items['ITEM_ELECTRIUM_Z'],
		items['ITEM_PSYCHIUM_Z'],
		items['ITEM_ICIUM_Z'],
		items['ITEM_DRAGONIUM_Z'],
		items['ITEM_DARKINIUM_Z'],
		items['ITEM_FAIRIUM_Z'],
		]

items_any = items_any_held + items_nonheld_nontm

items_berries = [
		items['ITEM_CHERI_BERRY'],
		items['ITEM_CHESTO_BERRY'],
		items['ITEM_PECHA_BERRY'],
		items['ITEM_RAWST_BERRY'],
		items['ITEM_ASPEAR_BERRY'],
		items['ITEM_LEPPA_BERRY'],
		items['ITEM_ORAN_BERRY'],
		items['ITEM_PERSIM_BERRY'],
		items['ITEM_LUM_BERRY'],
		items['ITEM_SITRUS_BERRY'],
		items['ITEM_FIGY_BERRY'],
		items['ITEM_WIKI_BERRY'],
		items['ITEM_MAGO_BERRY'],
		items['ITEM_AGUAV_BERRY'],
		items['ITEM_IAPAPA_BERRY'],
		items['ITEM_RAZZ_BERRY'],
		items['ITEM_BLUK_BERRY'],
		items['ITEM_NANAB_BERRY'],
		items['ITEM_WEPEAR_BERRY'],
		items['ITEM_PINAP_BERRY'],
		items['ITEM_POMEG_BERRY'],
		items['ITEM_KELPSY_BERRY'],
		items['ITEM_QUALOT_BERRY'],
		items['ITEM_HONDEW_BERRY'],
		items['ITEM_GREPA_BERRY'],
		items['ITEM_TAMATO_BERRY'],
		items['ITEM_CORNN_BERRY'],
		items['ITEM_MAGOST_BERRY'],
		items['ITEM_RABUTA_BERRY'],
		items['ITEM_NOMEL_BERRY'],
		items['ITEM_SPELON_BERRY'],
		items['ITEM_PAMTRE_BERRY'],
		items['ITEM_WATMEL_BERRY'],
		items['ITEM_DURIN_BERRY'],
		items['ITEM_BELUE_BERRY'],
		items['ITEM_OCCA_BERRY'],
		items['ITEM_PASSHO_BERRY'],
		items['ITEM_WACAN_BERRY'],
		items['ITEM_RINDO_BERRY'],
		items['ITEM_YACHE_BERRY'],
		items['ITEM_CHOPLE_BERRY'],
		items['ITEM_KEBIA_BERRY'],
		items['ITEM_SHUCA_BERRY'],
		items['ITEM_COBA_BERRY'],
		items['ITEM_PAYAPA_BERRY'],
		items['ITEM_TANGA_BERRY'],
		items['ITEM_CHARTI_BERRY'],
		items['ITEM_KASIB_BERRY'],
		items['ITEM_HABAN_BERRY'],
		items['ITEM_COLBUR_BERRY'],
		items['ITEM_BABIRI_BERRY'],
		items['ITEM_CHILAN_BERRY'],
		items['ITEM_ROSELI_BERRY'],
		items['ITEM_LIECHI_BERRY'],
		items['ITEM_GANLON_BERRY'],
		items['ITEM_SALAC_BERRY'],
		items['ITEM_PETAYA_BERRY'],
		items['ITEM_APICOT_BERRY'],
		items['ITEM_LANSAT_BERRY'],
		items['ITEM_STARF_BERRY'],
		items['ITEM_MICLE_BERRY'],
		items['ITEM_ENIGMA_BERRY'],
		items['ITEM_CUSTAP_BERRY'],
		items['ITEM_JABOCA_BERRY'],
		items['ITEM_ROWAP_BERRY'],
		items['ITEM_KEE_BERRY'],
		items['ITEM_MARANGA_BERRY'],
		]

items_tm = [
		items['ITEM_TM01'],
		items['ITEM_TM02'],
		items['ITEM_TM03'],
		items['ITEM_TM04'],
		items['ITEM_TM05'],
		items['ITEM_TM06'],
		items['ITEM_TM07'],
		items['ITEM_TM08'],
		items['ITEM_TM09'],
		items['ITEM_TM10'],
		items['ITEM_TM11'],
		items['ITEM_TM12'],
		items['ITEM_TM13'],
		items['ITEM_TM14'],
		items['ITEM_TM15'],
		items['ITEM_TM16'],
		items['ITEM_TM17'],
		items['ITEM_TM18'],
		items['ITEM_TM19'],
		items['ITEM_TM20'],
		items['ITEM_TM21'],
		items['ITEM_TM22'],
		items['ITEM_TM23'],
		items['ITEM_TM24'],
		items['ITEM_TM25'],
		items['ITEM_TM26'],
		items['ITEM_TM27'],
		items['ITEM_TM28'],
		items['ITEM_TM29'],
		items['ITEM_TM30'],
		items['ITEM_TM31'],
		items['ITEM_TM32'],
		items['ITEM_TM33'],
		items['ITEM_TM34'],
		items['ITEM_TM35'],
		items['ITEM_TM36'],
		items['ITEM_TM37'],
		items['ITEM_TM38'],
		items['ITEM_TM39'],
		items['ITEM_TM40'],
		items['ITEM_TM41'],
		items['ITEM_TM42'],
		items['ITEM_TM43'],
		items['ITEM_TM44'],
		items['ITEM_TM45'],
		items['ITEM_TM46'],
		items['ITEM_TM47'],
		items['ITEM_TM48'],
		items['ITEM_TM49'],
		items['ITEM_TM50']
		]

if args.seed is None:
	print('INFO Seed is system time')
	random.seed(None,version=2)
else:
	print('INFO Seed is %s'%args.seed)
	random.seed(args.seed,version=2)

mon_cea = mon_options.copy()
random.shuffle(mon_cea)

def get_mon_cea():
	global mon_cea
	if len(mon_cea) == 0:
		mon_cea = mon_options.copy()
		random.shuffle(mon_cea)
	return mon_cea.pop()

def get_mon_ncea():
	global mon_options
	return random.choice(mon_options)

def get_item_berry():
	global items_berries
	return random.choice(items_berries)

def get_item_any():
	global items_any
	return random.choice(items_any)

def get_item_tm():
	global items_tm
	return random.choice(items_tm)

mon_eids = {}
item_eids = {}

def get_mon_eid(eid_val):
	global mon_eids
	return mon_eids.setdefault(eid_val,get_mon_ncea())

def get_item_eid(eid_val,item_type):
	global mon_eids
	global item_eids
	global megas

	if eid_val in item_eids:
		return item_eids[eid_val]

	item = None

	if item_type == 'gift':
		mon = get_mon_eid(eid_val)
		if mon in items_held_gift:
			(common,rare) = items_held_gift[mon]
			chance = random.randint(0,100)
			if chance < 50:
				item = random.choice(common)
			elif rare is not None and chance < 55:
				item = rare
			else:
				item = random.choice(items_any)
		else:
			item = random.choice(items_any)
	elif item_type == 'held':
		mon = get_mon_eid(eid_val)
		if mon in items_foe_held:
			(common,rare) = items_foe_held[mon]
			chance = random.randint(0,100)
			if chance < 50:
				item = random.choice(common)
			elif rare is not None and chance < 55:
				item = rare
			else:
				item = random.choice(items_any_held)
		else:
			item = random.choice(items_any_held)
	elif item_type == 'tm':
		item = get_item_tm()
	elif item_type == 'berry':
		item = get_item_berry()
	elif item_type == 'any':
		item = get_item_any()
	else:
		print('WARN unrecognized item type %s'%item_type)
	return item_eids.setdefault(eid_val,item)

shutil.copy(args.rom,args.randomized)
with open(args.randomized,'r+b') as randomized:
	for entry in pkmn_offsets:
		(addr,cea,eid) = entry
		randomized.seek(addr)
		mon = None
		if eid is None:
			if cea:
				mon = get_mon_cea()
			else:
				mon = get_mon_ncea()
		else:
			mon = get_mon_eid(eid)
		if mon == None:
			continue
		bytes_to_write = mon.to_bytes(2,byteorder='little')
		randomized.write(bytes_to_write)
	for entry in item_offsets:
		(addr,item_type,eid) = entry
		randomized.seek(addr)
		item = None
		if eid is None:
			if item_type == 'gift':
				item = get_item_any()
			elif item_type == 'held':
				item = get_item_any()
			elif item_type == 'tm':
				item = get_item_tm()
			elif item_type == 'berry':
				item = get_item_berry()
			elif item_type == 'any':
				item = get_item_any()
			else:
				print('WARN unrecognized item type %s'%item_type)
		else:
			item = get_item_eid(eid,item_type)
		if item is None:
			continue
		bytes_to_write = item.to_bytes(2,byteorder='little')
		randomized.write(bytes_to_write)
